### ISSUE TITLE
wai-middleware-caching-redis-0.2.0.0 fails to build with hedis-0.16.1

### ISSUE THREAD

**Issue by juhp** [yogsototh/wai-middleware-caching#2]
For stackage nightly:

```
       Building library for wai-middleware-caching-redis-0.2.0.0...                                                                 
       [1 of 1] Compiling Network.Wai.Middleware.RedisCache
       /home/curators/work/unpack-dir/unpacked/wai-middleware-caching-redis-0.2.0.0-fbac5f1b6bbb98e3893560bb3a31f4252b00294ee69ed98b537e14d5c8ba3df5/src/Network/Wai/Middleware/RedisCache.hs:23:74: error: [GHC-61689]                                                 
           Module ‘Database.Redis’ does not export ‘PortID(..)’.
          |                                                       
       23 | import           Database.Redis            (ConnectInfo(..), Connection, PortID(..), connect,
          |                                                                          ^^^^^^^^^^
```

https://github.com/commercialhaskell/stackage/issues/8017
